# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d62bf51a38ac9b7960435861631ccc2add6a529669e984dc8892e66f8e58ce23ac754913b1b5cee46c9e45b48b948bd6ec1b9113f3234736ccd305cbc62136c8

test:
  secret_key_base: 5dc1f98f4786799fe23a96c5bc30a6ec192665dee6babcafc7c8c4c94be0ca8b5e02d86fbfd4e1142457f6cf9abf5cd6e2d0ee9af9490e8af093f938584b46aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
